# Numpy

In [5]:
import numpy as np

## Let's do some basic stuff

In [9]:
a = np.array([1,3,4])
a

array([1, 3, 4])

In [10]:
a*2

array([2, 6, 8])

In [12]:
a = np.arange(10)

#### You can reshape it by 2D or 3D (a.reshape(2,5,2)) and ... 

In [15]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
a = a.reshape(2,5)

In [19]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(2, 5)
2
10
int64


In [24]:
a = np.zeros((3,4))
b = np.ones((4,5))
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Some operations

In [25]:
a = np.array([11,22,33,44])
b = np.arange(4)

In [37]:
c = a * b
d = [1,2,3] 
h = [1,2,5]
print(d*2,c)

[1, 2, 3, 1, 2, 3] [  0  22  66 132]


In [38]:
a - b

array([11, 21, 31, 41])

In [41]:
c

array([  0,  22,  66, 132])

In [40]:
c > 50

array([False, False,  True,  True])

In [42]:
np.sin(c)

array([ 0.        , -0.00885131, -0.02655115,  0.05308359])