# Pandas

In [10]:
import pandas as pd
import numpy as np

In [11]:
pd.Series([1,2,"mamad",0,np.nan , -10])

0        1
1        2
2    mamad
3        0
4      NaN
5      -10
dtype: object

In [14]:
dates = pd.date_range("20210101",periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
rand = np.random.rand(6,4)
randn = np.random.randn(6,4)
print(rand, randn)

[[0.16433094 0.97680326 0.88771428 0.57939356]
 [0.94303141 0.41250893 0.60956614 0.02738412]
 [0.13140133 0.48182812 0.11945566 0.87184153]
 [0.03920651 0.09438436 0.87166319 0.48613289]
 [0.85798951 0.62382441 0.14545188 0.98582216]
 [0.76020669 0.39956377 0.6857468  0.99756604]] [[ 0.07329338  0.85060689  0.49477433  0.21620116]
 [-0.05334978  0.93253507  0.7336345  -0.72847878]
 [ 0.04595801 -0.98138606  1.36451136 -1.57031814]
 [-1.55042657  1.71409263 -0.58395171 -0.25332123]
 [ 1.28259643 -1.30477942 -0.38023284 -0.41139588]
 [-0.24293583  1.54395563  1.31662157 -0.70903364]]


In [31]:
df_dates_index = pd.DataFrame(rand, index=dates)
df_normal = pd.DataFrame(rand)
df_dates_index

0         1         2         3
2021-01-01  0.164331  0.976803  0.887714  0.579394
2021-01-02  0.943031  0.412509  0.609566  0.027384
2021-01-03  0.131401  0.481828  0.119456  0.871842
2021-01-04  0.039207  0.094384  0.871663  0.486133
2021-01-05  0.857990  0.623824  0.145452  0.985822
2021-01-06  0.760207  0.399564  0.685747  0.997566

In [26]:
df_normal

0         1         2         3
0  0.164331  0.976803  0.887714  0.579394
1  0.943031  0.412509  0.609566  0.027384
2  0.131401  0.481828  0.119456  0.871842
3  0.039207  0.094384  0.871663  0.486133
4  0.857990  0.623824  0.145452  0.985822
5  0.760207  0.399564  0.685747  0.997566

In [32]:
df = pd.DataFrame(rand, index=dates, columns=['a','b','c','d'])
df

a         b         c         d
2021-01-01  0.164331  0.976803  0.887714  0.579394
2021-01-02  0.943031  0.412509  0.609566  0.027384
2021-01-03  0.131401  0.481828  0.119456  0.871842
2021-01-04  0.039207  0.094384  0.871663  0.486133
2021-01-05  0.857990  0.623824  0.145452  0.985822
2021-01-06  0.760207  0.399564  0.685747  0.997566

In [33]:
df["A"]

KeyError: 'A'

In [35]:
df['a']

2021-01-01    0.164331
2021-01-02    0.943031
2021-01-03    0.131401
2021-01-04    0.039207
2021-01-05    0.857990
2021-01-06    0.760207
Freq: D, Name: a, dtype: float64

In [38]:
df.head(2)
df.tail(3)

a         b         c         d
2021-01-04  0.039207  0.094384  0.871663  0.486133
2021-01-05  0.857990  0.623824  0.145452  0.985822
2021-01-06  0.760207  0.399564  0.685747  0.997566

In [39]:
df.describe()

a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean   0.482694  0.498152  0.553266  0.658023
std    0.412605  0.291633  0.343062  0.374672
min    0.039207  0.094384  0.119456  0.027384
25%    0.139634  0.402800  0.261480  0.509448
50%    0.462269  0.447169  0.647656  0.725618
75%    0.833544  0.588325  0.825184  0.957327
max    0.943031  0.976803  0.887714  0.997566

In [46]:
df["a"].max()
df["a"].min()
df["a"].count()
df["a"].mean()

0.4826943984862205

In [50]:
df[4:6]

a         b         c         d
2021-01-05  0.857990  0.623824  0.145452  0.985822
2021-01-06  0.760207  0.399564  0.685747  0.997566

In [52]:
df.T

2021-01-01  2021-01-02  2021-01-03  2021-01-04  2021-01-05  2021-01-06
a    0.164331    0.943031    0.131401    0.039207    0.857990    0.760207
b    0.976803    0.412509    0.481828    0.094384    0.623824    0.399564
c    0.887714    0.609566    0.119456    0.871663    0.145452    0.685747
d    0.579394    0.027384    0.871842    0.486133    0.985822    0.997566

In [54]:
df.sort_values(by='b')

a         b         c         d
2021-01-04  0.039207  0.094384  0.871663  0.486133
2021-01-06  0.760207  0.399564  0.685747  0.997566
2021-01-02  0.943031  0.412509  0.609566  0.027384
2021-01-03  0.131401  0.481828  0.119456  0.871842
2021-01-05  0.857990  0.623824  0.145452  0.985822
2021-01-01  0.164331  0.976803  0.887714  0.579394

In [55]:
df[df['a']>0.2]

a         b         c         d
2021-01-02  0.943031  0.412509  0.609566  0.027384
2021-01-05  0.857990  0.623824  0.145452  0.985822
2021-01-06  0.760207  0.399564  0.685747  0.997566